- uri:
    url: "http://{{ item }}:5000/"
    return_content: yes
  register: webpage
  with_items:    
    #- 'leaf01'
    - 'leaf02'
    - 'leaf03'
    #- 'leaf04'

- debug: var=item.content
  failed_when: item.content|int < 2
  with_items: "{{ webpage.results }}"
