  - name: Get number of bgp neighbors
    shell: "vtysh -c 'show ip bgp summary' "
    register: number_neighbors

  - set_fact:
      output: "{{ number_neighbors.stdout_lines | bgp_neighbor_check() }}"

  - debug: var=output
